version: "3.8"
services:

  backend_db:
    image: mysql:8
    container_name: backend_db
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=${BACKEND_MYSQL_ROOT_PASSWORD}
      - MYSQL_DATABASE=${BACKEND_MYSQL_DB}
      - MYSQL_PASSWORD=${BACKEND_MYSQL_PASSWORD}
      - MYSQL_USER=${BACKEND_MYSQL_USER}
    volumes:
      - ./${DB_FOLDER}/${BACKEND_MYSQL_HOST}:/var/lib/mysql
    networks:
      - backend
    ports:
      - "3306:3306"

  backend:
    image: node:lts-alpine
    container_name: nestjs
    restart: always
    working_dir: /${BACKEND_WORKING_DIR}
    volumes:
      - .:/${BACKEND_WORKING_DIR}
      # - /${MS_GATEWAY_WORKING_DIR}/node_modules
    ports:
      - "3000:3000"
      - "9229:9229"
    networks:
      - backend
    environment:
      - START_TYPE
      - NODE_ENV
      - BACKEND_WORKING_DIR
    # build:
    #   context: .
    command: npm run start:${START_TYPE}

networks:
  frontend:
  backend:
