name: test
on:
  push:
    branches:
      - master
jobs:
  tests:
    name: tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-node@v1
        with:
          node-version: 10
      - name: Install dependencies
        run: yarn
      - name: Prisma generate
        run: yarn run prisma:generate
      - name: Run tests
        run: yarn run test
